name: Build & Draft Release

on:
  push:
    tags:
      - "v*"          # e.g., v0.0.1, v1.2.3
  workflow_dispatch:   # allow manual runs too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build (no daemon)
        run: ./gradlew --no-daemon clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: BuzzCore-jar
          path: build/libs/*.jar
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to create releases
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: BuzzCore-jar
          path: dist

      - name: Create draft GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          draft: true                 # <— stays as a draft until you publish it
          prerelease: false
          files: dist/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
